title: Yutong's Homepage # name of the site
author: Yutong Xie # name of site's author
# email: riccardo.graziosi97@gmail.com # email of site's author
url: https://yutxie.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
# description: > # description of the site (multiple lines allowed)
#   A (nearly) no-CSS, fast, minimalist Jekyll theme.

permalink: /:slug.html

favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
theme: no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "(click here to get back to the root)" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

collections:
  pages:
    output: true
    permalink: /:name
